SELECT * FROM EMPLOYEES

--SQL QUERY TO FIND THE SECOND HIGHEST SALARY

WITH CTE as
(SELECT *,
DENSE_RANK() OVER (ORDER BY SALARY DESC)AS DRNK
FROM EMPLOYEES)
SELECT * FROM CTE WHERE DRNK=2


--SQL QUERY TO FIND SECOND HIGHEST SALARY FROM EACH DEPARTMENT

WITH CTE as
(SELECT *,
DENSE_RANK() OVER (PARTITION BY DEPARTMENT ORDER BY SALARY DESC)AS DRNK
FROM EMPLOYEES)
SELECT * FROM CTE WHERE DRNK=2